apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: backend-web
    literals:
      - DEBUG=1
      - OIDC_PROVIDER=https://auth.apex.local/realms/apex
      - OIDC_BACKCHANNEL=https://auth-service.apex.svc.cluster.local:8443/realms/apex
      - INSECURE_TLS=1
      - DOMAIN=api.apex.local
      - REDIRECT_URL=https://apex.local/#/login
      - ORIGINS=https://apex.local
      - BACKEND=http://apiserver:8080
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/component: backend-web
  app.kubernetes.io/instance: backend-web
  app.kubernetes.io/name: backend-web
