apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - persistentvolumeclaim.yaml
  - service.yaml
  - statefulset.yaml
commonLabels:
  app.kubernetes.io/component: ipam
  app.kubernetes.io/instance: ipam
  app.kubernetes.io/name: ipam
