apiVersion: v1
kind: Service
metadata:
  name: ipam
spec:
  selector:
    app.kubernetes.io/component: ipam
    app.kubernetes.io/instance: ipam
    app.kubernetes.io/name: ipam
  ports:
    - port: 9090
      targetPort: 9090
