version: "3.7"

services:
  ipam-db:
    image: docker.io/library/postgres
    environment:
      - POSTGRES_USER=${IPAM_DB_USER}
      - POSTGRES_PASSWORD=${IPAM_DB_PASSWORD}
    networks:
      - default

  ipam:
    image: ghcr.io/metal-stack/go-ipam
    depends_on:
      - ipam-db
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --grpc-server-endpoint=0.0.0.0:9090
      - postgres
      - --host=${IPAM_DB_HOST}
      - --dbname=ipam
      - --user=${IPAM_DB_USER}
      - --password=${IPAM_DB_PASSWORD}
    networks:
      - default

  apiserver-db:
    image: docker.io/library/postgres
    environment:
      - POSTGRES_USER=${APISERVER_DB_USER}
      - POSTGRES_PASSWORD=${APISERVER_DB_PASSWORD}
    networks:
      - default

  apiserver:
    image: quay.io/apex/apiserver:latest
    depends_on:
      - apiserver-db
      - ipam
      - dex
    build:
      context: .
      dockerfile: ./Containerfile.apiserver
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      APEX_DEBUG: 1
      APEX_DB_HOST: ${APISERVER_DB_HOST}
      APEX_DB_NAME: ${APISERVER_DB_USER}
      APEX_DB_USER: ${APISERVER_DB_USER}
      APEX_DB_PASSWORD: ${APISERVER_DB_PASSWORD}
      APEX_IPAM_URL: ${IPAM_ADDRESS}
      APEX_OIDC_URL: ${APEX_OIDC_URL}
      APEX_OIDC_CLIENT_ID_WEB: ${APEX_OIDC_CLIENT_ID}
      APEX_OIDC_CLIENT_ID_CLI: ${APEX_OIDC_CLIENT_ID_CLI}
    networks:
      - default

  ui:
    image: quay.io/apex/apiserver-ui:latest
    depends_on:
     - apiserver
     - keycloak
    build:
      context: .
      dockerfile: ./Containerfile.ui
    networks:
      - default

  bff-web:
    depends_on:
      - apiserver
      - dex
    image: quay.io/go-oidc-agent/go-oidc-agent:latest
    environment:
      DEBUG: 1
      OIDC_PROVIDER: ${APEX_OIDC_URL}
      OIDC_CLIENT_ID: ${APEX_OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${APEX_OIDC_CLIENT_SECRET}
      REDIRECT_URL: ${UI_URL}/#/login
      ORIGINS: ${UI_URL}
      DOMAIN: ${API_URL}
      BACKEND: http://apiserver:8080
    networks:
      - default

  bff-cli:
    depends_on:
      - apiserver
      - dex
    image: quay.io/go-oidc-agent/go-oidc-agent:latest
    environment:
      DEBUG: 1
      OIDC_PROVIDER: ${APEX_OIDC_URL}
      OIDC_CLIENT_ID: ${APEX_OIDC_CLIENT_ID_CLI}
      OIDC_FLOW: device
      BACKEND: http://apiserver:8080
    networks:
      - default

  dex:
    image: ghcr.io/dexidp/dex:v2.35.2
    volumes:
      - ./hack/auth.yaml:/etc/dex/config.yaml:ro,z
    command:
      - dex
      - serve
      - /etc/dex/config.yaml
    networks:
      default:
        aliases:
          - auth.apex.local

  proxy:
    depends_on:
     - apiserver
     - dex
     - ui
    image: docker.io/library/caddy:2.6-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,z

networks:
  default:
