apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  labels:
    app.kubernetes.io/component: dex
    app.kubernetes.io/instance: dex
    app.kubernetes.io/name: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: dex
      app.kubernetes.io/instance: dex
      app.kubernetes.io/name: dex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: dex
        app.kubernetes.io/instance: dex
        app.kubernetes.io/name: dex
    spec:
      containers:
        - name: dex
          image: ghcr.io/dexidp/dex:v2.35.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          env:
            - name: WEB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dex-secrets
                  key: web-client-secret
                  optional: false
          args:
            - dex
            - serve
            - /etc/dex/config.yaml
          volumeMounts:
          - name: config
            mountPath: /etc/dex
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: dex
