apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dex
spec:
  rules:
    - host: <AUTH_HOST>
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: dex
                port:
                  number: 80
