apiVersion: v1
kind: Service
metadata:
  name: dex
spec:
  selector:
    app.kubernetes.io/instance: dex
    app.kubernetes.io/name: dex
  ports:
    - name: https
      port: 443
      targetPort: 5554
