apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - issuer.yaml
namespace: apex
configMapGenerator:
  - name: auth-config
    behavior: replace
    literals:
      - hostname=auth.apex-hosted.cloud
      - frontend-url=https://apex-hosted.cloud
  - name: realm
    behavior: replace
    files:
      - files/apex.json
patchesJson6902:
  - patch: |-
      - op: replace
        path: /data/APEX_OIDC_URL
        value: https://auth.apex-hosted.cloud
    target:
      kind: ConfigMap
      name: apiserver
  - patch: |-
      - op: replace
        path: /data/DOMAIN
        value: https://api.apex-hosted.cloud
      - op: replace
        path: /data/OIDC_PROVIDER
        value: https://auth.apex-hosted.cloud
      - op: replace
        path: /data/ORIGINS
        value: https://apex-hosted.cloud
      - op: replace
        path: /data/REDIRECT_URL
        value: https://apex-hosted.cloud/#/login
    target:
      kind: ConfigMap
      name: backend-web
  - patch: |-
      - op: replace
        path: /data/DOMAIN
        value: https://api.apex-hosted.cloud
      - op: replace
        path: /data/OIDC_PROVIDER
        value: https://auth.apex-hosted.cloud
    target:
      kind: ConfigMap
      name: backend-cli
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.apex-hosted.cloud
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.apex-hosted.cloud
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: apiproxy
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: auth.apex-hosted.cloud
      - op: replace
        path: /spec/tls/0/hosts/0
        value: auth.apex-hosted.cloud
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: dex
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: apex-hosted.cloud
      - op: replace
        path: /spec/tls/0/hosts/0
        value: apex-hosted.cloud
      - op: replace
        path: /metadata/annotations/cert-manager.io~1issuer
        value: letsencrypt
    target:
      kind: Ingress
      name: frontend
images:
  - name: quay.io/apex/apiserver
    newTag: 19d502e9845edced47ca5acb73af525b54f06c6d
  - name: quay.io/apex/frontend
    newTag: 19d502e9845edced47ca5acb73af525b54f06c6d
