apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-web
spec:
  template:
    spec:
      containers:
        - name: backend-web
          env:
            - name: DOMAIN
              value: api.apex.local
