apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apiserver
spec:
  template:
    spec:
      containers:
        - name: apiserver
          env:
            - name: APEX_OIDC_URL
              value: http://auth.apex.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-cli
spec:
  template:
    spec:
      containers:
        - name: backend-cli
          env:
            - name: OIDC_PROVIDER
              value: http://auth.apex.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-web
spec:
  template:
    spec:
      containers:
        - name: backend-web
          env:
            - name: OIDC_PROVIDER
              value: http://auth.apex.local
