apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: backend-cli
    literals:
      - DEBUG=1
      - OIDC_PROVIDER=https://auth.apex.local/realms/apex
      - OIDC_BACKCHANNEL=https://auth.apex.svc.cluster.local:8443/realms/apex
      - INSECURE_TLS=1
      - OIDC_FLOW=device
      - DOMAIN=api.apex.local
      - BACKEND=http://apiserver:8080
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/component: backend-cli
  app.kubernetes.io/instance: backend-cli
  app.kubernetes.io/name: backend-cli
