apiVersion: v1
kind: Service
metadata:
  name: backend-web
  labels:
    app.kubernetes.io/component: backend-web
    app.kubernetes.io/instance: backend-web
    app.kubernetes.io/name: backend-web
spec:
  selector:
    app.kubernetes.io/component: backend-web
    app.kubernetes.io/instance: backend-web
    app.kubernetes.io/name: backend-web
  ports:
    - port: 8080
      targetPort: 8080
