kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apiserver-postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 5Gi # Sets volume size
