apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
commonLabels:
  app.kubernetes.io/component: database
  app.kubernetes.io/instance: database
  app.kubernetes.io/name: database
