apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: backend-cli
      app.kubernetes.io/instance: backend-cli
      app.kubernetes.io/name: backend-cli
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend-cli
        app.kubernetes.io/instance: backend-cli
        app.kubernetes.io/name: backend-cli
    spec:
      containers:
        - name: backend-cli
          image: quay.io/go-oidc-agent/go-oidc-agent:2d47eec2d27c3eaa0221ddbb0a07c8ca55dbe4bf
          imagePullPolicy: IfNotPresent
          env:
            - name: DEBUG
              value: "1"
            - name: OIDC_PROVIDER
              value: <AUTH_HOST>
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: dex-secrets
                  key: cli-client-id
                  optional: false
            - name: OIDC_FLOW
              value: device
            - name: BACKEND
              value: http://apiserver:8080
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
      restartPolicy: Always
