apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/component: backend-cli
  app.kubernetes.io/instance: backend-cli
  app.kubernetes.io/name: backend-cli
