apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: apiproxy
      app.kubernetes.io/instance: apiproxy
      app.kubernetes.io/name: apiproxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: apiproxy
        app.kubernetes.io/instance: apiproxy
        app.kubernetes.io/name: apiproxy
    spec:
      containers:
        - name: caddy
          image: docker.io/library/caddy:2.6-alpine
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: caddyfile
