apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - keycloak.yaml
  - ingress.yaml
  - realm.yaml
secretGenerator:
  - name: auth-secrets
    literals:
      - web-client-id=apex-web
      - web-client-secret=dhEN2dsqyUg5qmaDAdqi4CmH
      - cli-client-id=apex-cli
commonLabels:
  app.kubernetes.io/component: auth
  app.kubernetes.io/instance: auth
  app.kubernetes.io/name: auth
