apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
configMapGenerator:
  - name: auth-config
    literals:
      - hostname=auth.apex.local
      - frontend-url=https://apex.local
  - name: realm
    files:
      - files/apex.json
secretGenerator:
  - name: auth-secrets
    literals:
      - keycloak-admin-password=floofykittens
      - web-client-id=apex-web
      - web-client-secret=dhEN2dsqyUg5qmaDAdqi4CmH
      - cli-client-id=apex-cli
commonLabels:
  app.kubernetes.io/component: auth
  app.kubernetes.io/instance: auth
  app.kubernetes.io/name: auth
