apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: dex
    files:
      - files/config.yaml
  - name: caddyfile
    files:
      - files/Caddyfile
