apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: apiserver
          image: quay.io/apex/apiserver:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: APEX_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_DEBUG
            - name: APEX_DB_HOST
              valueFrom:
                secretKeyRef: 
                  name: apiserverdb-pguser-apiserverdb
                  key: host
            - name: APEX_DB_NAME
              valueFrom:
                secretKeyRef: 
                  name: apiserverdb-pguser-apiserverdb
                  key: dbname
            - name: APEX_DB_USER
              valueFrom:
                secretKeyRef: 
                  name: apiserverdb-pguser-apiserverdb
                  key: user
            - name: APEX_DB_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: apiserverdb-pguser-apiserverdb
                  key: password
            - name: APEX_DB_SSLMODE
              value: require
            - name: APEX_IPAM_URL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_IPAM_URL
            - name: APEX_OIDC_URL
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_OIDC_URL
            - name: APEX_OIDC_CLIENT_ID_WEB
              valueFrom:
                secretKeyRef:
                  name: dex-secrets
                  key: web-client-id
                  optional: false
            - name: APEX_OIDC_CLIENT_ID_CLI
              valueFrom:
                secretKeyRef:
                  name: dex-secrets
                  key: cli-client-id
                  optional: false
            - name: APEX_TRACE_ENDPOINT_OTLP
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_TRACE_ENDPOINT_OTLP
            - name: APEX_TRACE_INSECURE
              valueFrom:
                configMapKeyRef:
                  name: apiserver
                  key: APEX_TRACE_INSECURE
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 200Mi
      restartPolicy: Always
