apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: apiserver
    literals:
      - APEX_DEBUG=1
      - APEX_DB_HOST=localhost
      - APEX_DB_NAME=apiserver
      - APEX_DB_USER=apiserver
      - APEX_DB_PASSWORD=floofykittens
      - APEX_IPAM_URL=http://ipam:9090
      - APEX_OIDC_URL=https://auth.apex.local
      - APEX_TRACE_ENDPOINT_OTLP=""
      - APEX_TRACE_INSECURE="1"
resources:
  - persistentvolumeclaim.yaml
  - service.yaml
  - statefulset.yaml
commonLabels:
  app.kubernetes.io/component: apiserver
  app.kubernetes.io/instance: apiserver
  app.kubernetes.io/name: apiserver
