apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: caddyfile
    files:
      - files/Caddyfile
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/component: apiproxy
  app.kubernetes.io/instance: apiproxy
  app.kubernetes.io/name: apiproxy
