---
# tasks file for start-apex-agent
- name: Kill any existing apexd process from previous runs
  become: yes
  shell: |
    sudo killall apexd 2> /dev/null
  ignore_errors: yes

- name: Attach the Node Agent to the Controller
  become: yes
  shell: |
    apexd \
    --username '{{ apex_auth_uid }}' \
     s--password '{{ apex_auth_password }}' \
    {{ apex_url }} > apex-logs.txt 2>&1 &
